package com.erp.backend_service.exception;

/**
 * Định nghĩa tập hợp các mã lỗi nghiệp vụ dùng chung trong hệ thống,
 * mỗi mã gồm HTTP status, code và thông báo mặc định.
 */
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(500, "ERR_500", "Lỗi không xác định"),
    INVALID_KEY(400, "ERR_400", "Khóa không hợp lệ"),
    BAD_REQUEST(400, "ERR_400_BAD_REQUEST", "Yêu cầu không hợp lệ"),
    INVALID_REQUEST(400, "ERR_400_INVALID_REQUEST", "Yêu cầu không hợp lệ"),
    DUPLICATE_RESOURCE(409, "ERR_409_DUPLICATE", "Tài nguyên đã tồn tại"),
    RESOURCE_NOT_FOUND(404, "ERR_404_NOT_FOUND", "Không tìm thấy tài nguyên"),
    USER_EXISTED(400, "ERR_400_USER_EXISTED", "Người dùng đã tồn tại"),
    USER_NOT_EXISTED(404, "ERR_404_USER_NOT_EXISTED", "Người dùng không tồn tại"),
    UNAUTHENTICATED(401, "ERR_401", "Chưa xác thực"),
    UNAUTHORIZED(403, "ERR_403", "Bạn không có quyền truy cập"),
    INVALID_TOKEN(401, "ERR_401_INVALID_TOKEN", "Token không hợp lệ hoặc đã hết hạn"),
    TOKEN_REVOKED(401, "ERR_401_TOKEN_REVOKED", "Token đã bị thu hồi"),
    ACCOUNT_DISABLED(403, "ERR_403_ACCOUNT_DISABLED", "Tài khoản đã bị vô hiệu hóa hoặc tạm khóa"),
    TOO_MANY_REQUESTS(429, "ERR_429", "Quá nhiều yêu cầu, vui lòng thử lại sau"),
    BAD_CREDENTIALS(401, "ERR_401_BAD_CREDENTIALS", "Tên đăng nhập hoặc mật khẩu không đúng"),
    ACCOUNT_LOCKED(401, "ACCOUNT_LOCKED", "Tài khoản tạm thời bị khóa"),
    ASSIGNMENT_REQUIRED_FIELDS(400, "ASSIGNMENT_REQUIRED_FIELDS", "Tài khoản, vai trò và phạm vi là bắt buộc"),
    ASSIGNMENT_EXISTS(409, "ASSIGNMENT_EXISTS", "Phân vai trò và phạm vi đã tồn tại"),
    ACCOUNT_NOT_FOUND(404, "ACCOUNT_NOT_FOUND", "Không tìm thấy tài khoản"),
    CUSTOMER_NOT_FOUND(404, "CUSTOMER_NOT_FOUND", "Không tìm thấy khách hàng"),
    ACCOUNT_INACTIVE(401, "ACCOUNT_INACTIVE", "Tài khoản không hoạt động"),
    ROLE_NOT_FOUND(404, "ROLE_NOT_FOUND", "Không tìm thấy vai trò"),
    SCOPE_NOT_FOUND(404, "SCOPE_NOT_FOUND", "Không tìm thấy phạm vi"),
    PERMISSION_DENIED(403, "PERMISSION_DENIED", "Không có quyền thực hiện"),
    CROSS_SCOPE_DENIED(403, "CROSS_SCOPE_DENIED", "Dữ liệu nằm ngoài phạm vi được phân quyền"),
    CANNOT_MODIFY_ADMIN(400, "CANNOT_MODIFY_ADMIN", "Không thể thay đổi phân quyền của quản trị viên gốc"),
    ACCOUNT_SESSION_REVOKED(401, "ACCOUNT_SESSION_REVOKED", "Phiên đăng nhập của tài khoản đã bị thu hồi"),
    INTERNAL_ERROR(500, "INTERNAL_ERROR", "Lỗi dịch vụ nội bộ"),
    EMAIL_REQUIRED(400, "ERR_400_EMAIL_REQUIRED", "Cần cung cấp email để xác thực tài khoản"),
    OTP_INVALID(400, "ERR_400_OTP_INVALID", "Mã xác thực không hợp lệ"),
    OTP_EXPIRED(400, "ERR_400_OTP_EXPIRED", "Mã xác thực đã hết hạn, vui lòng yêu cầu mã mới"),
    OTP_ATTEMPTS_EXCEEDED(429, "ERR_429_OTP_ATTEMPTS", "Quá số lần thử sai, vui lòng yêu cầu mã mới"),
    PHONE_EXISTED(400, "ERR_400_PHONE_EXISTED", "Số điện thoại đã tồn tại"),
    EMAIL_EXISTED(400, "ERR_400_EMAIL_EXISTED", "Email đã tồn tại"),
    SUPPLIER_NOT_FOUND(404, "PROC_404_SUPPLIER_NOT_FOUND", "Không tìm thấy nhà cung cấp"),
    SUPPLIER_CODE_EXISTED(400, "PROC_400_SUPPLIER_CODE_EXISTED", "Mã nhà cung cấp đã được sử dụng"),
    SUPPLIER_TAX_CODE_EXISTED(400, "PROC_400_SUPPLIER_TAX_CODE_EXISTED",
                              "Mã số thuế đã được sử dụng bởi nhà cung cấp khác"),
    MATERIAL_NOT_FOUND(404, "PROC_404_MATERIAL_NOT_FOUND", "Không tìm thấy nguyên vật liệu"),
    SUPPLIER_MATERIAL_NOT_FOUND(404, "PROC_404_SUPPLIER_NOT_FOUND", "Không tìm thấy nguyên vật liệu của nhà cung cấp"),
    SUPPLIER_MATERIAL_EXISTS(409, "PROC_409_SUPPLIER_MATERIAL_EXISTS",
                             "Nhà cung cấp đã được liên kết với nguyên vật liệu này"),
    PROC_404_PO_NOT_FOUND(404, "PROC_404_PO_NOT_FOUND", "Đơn mua hàng không tồn tại."),
    PROC_400_PO_INVALID_STATUS_FOR_EDIT(400, "PROC_400_PO_INVALID_STATUS_FOR_EDIT",
                                        "Chỉ có thể chỉnh sửa đơn mua hàng ở trạng thái DRAFT."),
    PROC_400_PO_INVALID_STATUS_FOR_SUBMIT(400, "PROC_400_PO_INVALID_STATUS_FOR_SUBMIT",
                                          "Chỉ có thể trình duyệt đơn ở trạng thái DRAFT."),
    PROC_400_PO_INVALID_STATUS_FOR_APPROVE(400, "PROC_400_PO_INVALID_STATUS_FOR_APPROVE",
                                           "Chỉ có thể phê duyệt đơn ở trạng thái SUBMITTED."),
    PROC_400_PO_INVALID_STATUS_FOR_REJECT(400, "PROC_400_PO_INVALID_STATUS_FOR_REJECT",
                                          "Chỉ có thể từ chối đơn đang SUBMITTED."),
    PROC_400_PO_INVALID_STATUS_FOR_CANCEL(400, "PROC_400_PO_INVALID_STATUS_FOR_CANCEL",
                                          "Không thể hủy đơn mua hàng ở trạng thái hiện tại."),
    PROC_400_PO_INVALID_STATUS_FOR_RECEIVE(400, "PROC_400_PO_INVALID_STATUS_FOR_RECEIVE",
                                           "Chỉ có thể ghi nhận nhận hàng khi đơn ở trạng thái APPROVED hoặc PARTIALLY_RECEIVED."),
    PROC_400_PO_ITEMS_EMPTY(400, "PROC_400_PO_ITEMS_EMPTY", "Đơn đặt mua hàng phải có ít nhất một mặt hàng."),
    PROC_400_PO_INVALID_ITEM(400, "PROC_400_PO_INVALID_ITEM", "Dòng nguyên vật liệu không hợp lệ."),
    PROC_400_PO_INVALID_FILTER(400, "PROC_400_PO_INVALID_FILTER", "Khoảng ngày hoặc giá trị lọc không hợp lệ."),
    PROC_404_SUPPLIER_NOT_FOUND(404, "PROC_404_SUPPLIER_NOT_FOUND", "Không tìm thấy nhà cung cấp."),
    PROC_400_SUPPLIER_INACTIVE(400, "PROC_400_SUPPLIER_INACTIVE", "Nhà cung cấp đang ngừng hoạt động."),
    PROC_404_WAREHOUSE_NOT_FOUND(404, "PROC_404_WAREHOUSE_NOT_FOUND", "Không tìm thấy kho nhận."),
    PROC_400_WAREHOUSE_INACTIVE(400, "PROC_400_WAREHOUSE_INACTIVE", "Kho nhận đang ngừng hoạt động."),
    PROC_400_PO_INVALID_ORDER_DATE(400, "PROC_400_PO_INVALID_ORDER_DATE", "Ngày đặt hàng không hợp lệ."),
    PROC_400_PO_INVALID_EXPECTED_DATE(400, "PROC_400_PO_INVALID_EXPECTED_DATE",
                                      "Ngày dự kiến nhận phải bằng hoặc sau ngày đặt hàng."),
    PROC_400_PO_RECEIVED_EXCEED(400, "PROC_400_PO_RECEIVED_EXCEED",
                                "Số lượng nhận vượt quá số lượng đặt còn lại của dòng hàng."),
    PROC_400_PO_CANCEL_REASON_REQUIRED(400, "PROC_400_PO_CANCEL_REASON_REQUIRED", "Vui lòng nhập lý do hủy đơn."),
    PROC_400_PO_REJECT_REASON_REQUIRED(400, "PROC_400_PO_REJECT_REASON_REQUIRED", "Vui lòng nhập lý do từ chối."),
    PROC_400_PO_WAREHOUSE_MUST_BE_CENTRAL(400, "PROC_400_PO_WAREHOUSE_MUST_BE_CENTRAL",
                                         "Đơn mua hàng từ NCC chỉ được nhập về kho tổng. Chi nhánh nhận hàng qua phiếu chuyển kho từ kho tổng."),
    INV_400_MATERIAL_CODE_EXISTED(400, "INV_400_MATERIAL_CODE_EXISTED", "Mã nguyên vật liệu đã tồn tại."),
    INV_404_CATEGORY_NOT_FOUND(404, "INV_404_CATEGORY_NOT_FOUND", "Không tìm thấy danh mục."),
    INV_404_UNIT_NOT_FOUND(404, "INV_404_UNIT_NOT_FOUND", "Không tìm thấy đơn vị tính."),
    INV_400_UNIT_CODE_EXISTED(400, "INV_400_UNIT_CODE_EXISTED", "Mã đơn vị tính đã tồn tại."),
    INV_400_UNIT_IN_USE(400, "INV_400_UNIT_IN_USE",
                        "Đơn vị tính đã phát sinh dữ liệu và không thể xóa. Vui lòng chuyển sang INACTIVE."),
    MENU_400_CATEGORY_CODE_EXISTED(400, "MENU_400_CATEGORY_CODE_EXISTED", "Mã danh mục đã tồn tại trong loại này."),
    MENU_400_CATEGORY_IN_USE(400, "MENU_400_CATEGORY_IN_USE",
                             "Danh mục đang được sử dụng và không thể thay đổi. Vui lòng chuyển sang INACTIVE."),
    INV_400_INVALID_MATERIAL_CATEGORY(400, "INV_400_INVALID_MATERIAL_CATEGORY", "Danh mục phải thuộc nhóm MATERIAL."),
    INV_400_INVALID_MATERIAL_DATA(400, "INV_400_INVALID_MATERIAL_DATA", "Dữ liệu nguyên vật liệu không hợp lệ."),
    INV_400_MATERIAL_INVALID_STATUS(400, "INV_400_MATERIAL_INVALID_STATUS", "Trạng thái nguyên vật liệu không hợp lệ."),
    INV_400_MATERIAL_IN_USE(400, "INV_400_MATERIAL_IN_USE",
                            "Nguyên vật liệu đã phát sinh dữ liệu và không thể xóa. Vui lòng chuyển sang INACTIVE."),
    INV_404_WAREHOUSE_NOT_FOUND(404, "INV_404_WAREHOUSE_NOT_FOUND", "Không tìm thấy kho hàng."),
    INV_409_WAREHOUSE_CODE_EXISTED(409, "INV_409_WAREHOUSE_CODE_EXISTED", "Mã kho đã tồn tại."),
    INV_400_WAREHOUSE_IN_USE(400, "INV_400_WAREHOUSE_IN_USE", "Kho đã phát sinh dữ liệu (đơn mua hàng/tồn kho) và không thể xóa. Vui lòng chuyển sang INACTIVE."),
    INV_400_WAREHOUSE_INVALID_TYPE(400, "INV_400_WAREHOUSE_INVALID_TYPE", "Loại kho không hợp lệ. Chỉ chấp nhận CENTRAL hoặc BRANCH."),
    INV_400_WAREHOUSE_CENTRAL_NO_BRANCH(400, "INV_400_WAREHOUSE_CENTRAL_NO_BRANCH", "Kho loại CENTRAL không được gắn chi nhánh."),
    INV_400_WAREHOUSE_BRANCH_REQUIRED(400, "INV_400_WAREHOUSE_BRANCH_REQUIRED", "Kho loại BRANCH phải thuộc một chi nhánh đang hoạt động."),
    INV_400_WAREHOUSE_INVALID_STATUS(400, "INV_400_WAREHOUSE_INVALID_STATUS", "Trạng thái kho không hợp lệ."),
    INV_404_BRANCH_NOT_FOUND(404, "INV_404_BRANCH_NOT_FOUND", "Không tìm thấy chi nhánh."),
    INV_400_BRANCH_INACTIVE(400, "INV_400_BRANCH_INACTIVE", "Chi nhánh đang ngừng hoạt động."),
    PERMISSION_NOT_FOUND(404, "PERMISSION_NOT_FOUND", "Permission not found"),
    PERMISSION_CODE_EXISTS(409, "PERMISSION_CODE_EXISTS", "Permission code already exists"),
    PERMISSION_IN_USE(409, "PERMISSION_IN_USE", "Permission is still assigned to one or more roles"),
    SCOPE_IN_USE(409, "SCOPE_IN_USE", "Phạm vi vẫn đang được gán cho một hoặc nhiều tài khoản"),
    INV_400_INSUFFICIENT_STOCK(400, "INV_400_INSUFFICIENT_STOCK", "Tồn kho khả dụng không đủ."),
    INV_400_INVALID_STATUS(400, "INV_400_INVALID_STATUS", "Trạng thái phiếu không cho phép thực hiện thao tác này."),
    INV_400_WAREHOUSE_SAME(400, "INV_400_WAREHOUSE_SAME", "Kho nguồn và kho đích phải khác nhau."),
    INV_400_TRANSFER_BRANCH_MUST_RECEIVE_FROM_CENTRAL(400, "INV_400_TRANSFER_BRANCH_MUST_RECEIVE_FROM_CENTRAL",
                                                     "Kho chi nhánh chỉ được nhận hàng từ kho tổng. Hãy chọn kho tổng làm kho đi."),
    INV_400_ITEMS_EMPTY(400, "INV_400_ITEMS_EMPTY", "Phiếu phải có ít nhất một mặt hàng."),
    INV_400_DUPLICATE_MATERIAL(400, "INV_400_DUPLICATE_MATERIAL",
                               "Một mặt hàng không được xuất hiện nhiều lần trong cùng một phiếu."),
    INV_400_RECEIVE_EXCEED(400, "INV_400_RECEIVE_EXCEED", "Số lượng nhận vượt quá số lượng đang chuyển."),
    INV_400_COUNT_BELOW_RESERVED(400, "INV_400_COUNT_BELOW_RESERVED",
                                 "Số lượng kiểm kê không được nhỏ hơn số lượng đang giữ chỗ."),
    INV_400_COUNT_ALREADY_ADJUSTED(400, "INV_400_COUNT_ALREADY_ADJUSTED", "Phiếu kiểm kê đã được điều chỉnh."),
    INV_404_TRANSFER_NOT_FOUND(404, "INV_404_TRANSFER_NOT_FOUND", "Không tìm thấy phiếu chuyển kho."),
    INV_404_COUNT_NOT_FOUND(404, "INV_404_COUNT_NOT_FOUND", "Không tìm thấy phiếu kiểm kê."),
    INV_400_TRANSFER_CANNOT_EDIT(400, "INV_400_TRANSFER_CANNOT_EDIT",
                                 "Chỉ có thể chỉnh sửa phiếu chuyển kho ở trạng thái PENDING."),
    INV_400_COUNT_CANNOT_EDIT(400, "INV_400_COUNT_CANNOT_EDIT",
                              "Chỉ có thể chỉnh sửa phiếu kiểm kê ở trạng thái DRAFT hoặc IN_PROGRESS."),
    INV_400_COUNT_ITEMS_EMPTY(400, "INV_400_COUNT_ITEMS_EMPTY", "Phiếu kiểm kê phải có ít nhất một mặt hàng."),
    INV_400_COUNT_NOT_COMPLETED(400, "INV_400_COUNT_NOT_COMPLETED",
                                "Phiếu kiểm kê phải ở trạng thái COMPLETED trước khi điều chỉnh."),
    INV_400_TRANSFER_NOT_IN_TRANSIT(400, "INV_400_TRANSFER_NOT_IN_TRANSIT",
                                    "Phiếu chuyển kho chưa ở trạng thái IN_TRANSIT."),
    INV_400_TRANSFER_NOT_RECEIVABLE(400, "INV_400_TRANSFER_NOT_RECEIVABLE",
                                    "Phiếu chuyển kho không thể nhận ở trạng thái hiện tại."),
    INV_400_TRANSFER_CANCEL_REASON_REQUIRED(400, "INV_400_TRANSFER_CANCEL_REASON_REQUIRED",
                                            "Vui lòng nhập lý do hủy khi phiếu chuyển kho đang đi đường."),
    INV_400_WAREHOUSE_COUNTING(400, "INV_400_WAREHOUSE_COUNTING",
                               "Kho đang kiểm kê, không thể nhập/xuất/chuyển kho lúc này."),
    INV_400_COUNT_HAS_OPEN_TRANSFER(400, "INV_400_COUNT_HAS_OPEN_TRANSFER",
                                    "Kho còn phiếu chuyển đang đi đường, vui lòng nhận đủ hoặc hủy trước khi chốt kiểm kê."),
    INV_400_SYSTEM_VOUCHER_ONLY(400, "INV_400_SYSTEM_VOUCHER_ONLY",
                                "Chứng từ nguồn này do hệ thống tự sinh, không được tạo tay."),
    INV_404_STOCK_IN_NOT_FOUND(404, "INV_404_STOCK_IN_NOT_FOUND", "Phiếu nhập kho không tồn tại."),
    INV_404_STOCK_OUT_NOT_FOUND(404, "INV_404_STOCK_OUT_NOT_FOUND", "Phiếu xuất kho không tồn tại."),
    INV_404_MATERIAL_NOT_FOUND(404, "INV_404_MATERIAL_NOT_FOUND", "Không tìm thấy nguyên vật liệu."),
    INV_400_INVALID_PAGE(400, "INV_400_INVALID_PAGE", "Tham số page không hợp lệ: page phải là số nguyên không âm (page >= 0)."),
    INV_400_INVALID_SIZE(400, "INV_400_INVALID_SIZE", "Tham số size không hợp lệ: size phải lớn hơn 0 (size > 0)."),
    INV_400_STOCK_IN_ITEMS_EMPTY(400, "INV_400_STOCK_IN_ITEMS_EMPTY",
                                 "Phiếu nhập kho phải có ít nhất một dòng chi tiết."),
    INV_400_STOCK_OUT_ITEMS_EMPTY(400, "INV_400_STOCK_OUT_ITEMS_EMPTY",
                                  "Phiếu xuất kho phải có ít nhất một dòng chi tiết."),
    INV_400_INVALID_SOURCE_TYPE(400, "INV_400_INVALID_SOURCE_TYPE", "Loại nguồn nhập không hợp lệ."),
    INV_400_INVALID_DESTINATION_TYPE(400, "INV_400_INVALID_DESTINATION_TYPE", "Loại đích xuất không hợp lệ."),
    INV_400_STOCK_IN_INVALID_STATUS_FOR_EDIT(400, "INV_400_STOCK_IN_INVALID_STATUS_FOR_EDIT",
                                             "Chỉ có thể chỉnh sửa phiếu nhập kho ở trạng thái DRAFT."),
    INV_400_STOCK_OUT_INVALID_STATUS_FOR_EDIT(400, "INV_400_STOCK_OUT_INVALID_STATUS_FOR_EDIT",
                                              "Chỉ có thể chỉnh sửa phiếu xuất kho ở trạng thái DRAFT."),
    INV_400_STOCK_IN_INVALID_STATUS(400, "INV_400_STOCK_IN_INVALID_STATUS",
                                    "Không thể ghi sổ/hủy phiếu nhập kho ở trạng thái hiện tại."),
    INV_400_STOCK_OUT_INVALID_STATUS(400, "INV_400_STOCK_OUT_INVALID_STATUS",
                                     "Không thể ghi sổ/hủy phiếu xuất kho ở trạng thái hiện tại."),
    INV_400_OVER_RECEIPT(400, "INV_400_OVER_RECEIPT", "Số lượng nhập vượt quá số lượng đặt còn lại của dòng hàng."),
    INV_400_PO_INVALID_STATUS_FOR_RECEIVE(400, "INV_400_PO_INVALID_STATUS_FOR_RECEIVE",
                                          "Đơn mua hàng không ở trạng thái cho phép ghi nhận nhập kho."),
    INV_400_STOCK_IN_INVALID_FILTER(400, "INV_400_STOCK_IN_INVALID_FILTER",
                                    "Khoảng ngày hoặc giá trị lọc phiếu nhập không hợp lệ."),
    INV_400_STOCK_OUT_INVALID_FILTER(400, "INV_400_STOCK_OUT_INVALID_FILTER",
                                     "Khoảng ngày hoặc giá trị lọc phiếu xuất không hợp lệ."),
    INVALID_QUANTITY(400, "INVALID_QUANTITY", "Số lượng không hợp lệ."),
    MENU_404_PRODUCT_NOT_FOUND(404, "MENU_404_PRODUCT_NOT_FOUND", "Không tìm thấy sản phẩm."),
    MENU_409_PRODUCT_CODE_EXISTED(409, "MENU_409_PRODUCT_CODE_EXISTED", "Mã sản phẩm đã tồn tại trong hệ thống."),
    MENU_404_CATEGORY_NOT_FOUND(404, "MENU_404_CATEGORY_NOT_FOUND", "Không tìm thấy danh mục sản phẩm."),
    MENU_400_CATEGORY_INACTIVE(400, "MENU_400_CATEGORY_INACTIVE",
                               "Danh mục đã ngừng hoạt động, không thể thêm sản phẩm."),
    MENU_400_INVALID_PRODUCT_CATEGORY(400, "MENU_400_INVALID_PRODUCT_CATEGORY",
                                      "Danh mục sản phẩm/Combo bán trên POS phải thuộc nhóm PRODUCT."),
    MENU_400_PRODUCT_IMAGE_REQUIRED(400, "MENU_400_PRODUCT_IMAGE_REQUIRED", "Vui lòng chọn ảnh sản phẩm."),
    MENU_400_PRODUCT_IMAGE_TOO_LARGE(400, "MENU_400_PRODUCT_IMAGE_TOO_LARGE", "Ảnh sản phẩm không được vượt quá 5 MB."),
    MENU_400_PRODUCT_IMAGE_INVALID_TYPE(400, "MENU_400_PRODUCT_IMAGE_INVALID_TYPE",
                                        "Ảnh sản phẩm chỉ chấp nhận định dạng JPEG, PNG, WebP hoặc GIF."),
    MENU_500_STORAGE_UPLOAD_FAILED(500, "MENU_500_STORAGE_UPLOAD_FAILED", "Không thể tải ảnh lên máy chủ lưu trữ."),
    MENU_404_VARIANT_NOT_FOUND(404, "MENU_404_VARIANT_NOT_FOUND", "Không tìm thấy biến thể sản phẩm."),
    MENU_409_VARIANT_CODE_EXISTED(409, "MENU_409_VARIANT_CODE_EXISTED", "Mã biến thể đã tồn tại trong sản phẩm này."),
    MENU_400_VARIANT_IN_USE(400, "MENU_400_VARIANT_IN_USE", "Biến thể đang được liên kết trong công thức định lượng (BOM) hoặc đơn hàng, không thể xóa."),
    MENU_404_BOM_ITEM_NOT_FOUND(404, "MENU_404_BOM_ITEM_NOT_FOUND", "Không tìm thấy dòng nguyên vật liệu trong công thức."),
    MENU_409_BOM_MATERIAL_DUPLICATED(409, "MENU_409_BOM_MATERIAL_DUPLICATED", "Nguyên vật liệu này đã có trong công thức định lượng của biến thể."),
    MENU_400_BOM_ITEMS_EMPTY(400, "MENU_400_BOM_ITEMS_EMPTY", "Công thức định lượng phải có ít nhất một nguyên liệu."),
    MENU_404_UNIT_NOT_FOUND(404, "MENU_404_UNIT_NOT_FOUND", "Không tìm thấy đơn vị tính."),
    MENU_400_BOM_INVALID_QUANTITY(400, "MENU_400_BOM_INVALID_QUANTITY", "Định lượng nguyên vật liệu không hợp lệ."),
    MENU_400_BOM_INVALID_WASTAGE(400, "MENU_400_BOM_INVALID_WASTAGE", "Tỷ lệ hao hụt không hợp lệ."),
    MENU_400_BOM_UNIT_MISMATCH(400, "MENU_400_BOM_UNIT_MISMATCH", "Đơn vị BOM phải trùng đơn vị cơ sở của nguyên vật liệu."),
    MENU_400_BOM_MATERIAL_INACTIVE(400, "MENU_400_BOM_MATERIAL_INACTIVE", "Không được thêm nguyên vật liệu đang ngừng hoạt động vào BOM."),
    VOUCHER_CODE_EXISTED(409, "MENU_409_VOUCHER_CODE_EXISTED", "Mã voucher đã tồn tại."),
    VOUCHER_NOT_FOUND(404, "MENU_404_VOUCHER_NOT_FOUND", "Không tìm thấy voucher."),
    INVALID_DATE(400, "MENU_400_INVALID_DATE", "Thời gian hiệu lực voucher không hợp lệ."),
    INVALID_PRICE(400, "MENU_400_INVALID_PRICE", "Giá trị giảm giá voucher không hợp lệ."),
    VOUCHER_INVALID_USAGE_LIMIT(400, "MENU_400_INVALID_USAGE_LIMIT",
            "Giới hạn sử dụng voucher không hợp lệ (lượt dùng mỗi khách phải lớn hơn 0 và không vượt quá tổng lượt dùng tối đa)."),
    USAGE_LIMIT_EXCEEDED(400, "MENU_400_USAGE_LIMIT_EXCEEDED", "Voucher đã đạt giới hạn sử dụng."),
    VOUCHER_EXPIRED(400, "MENU_400_VOUCHER_EXPIRED", "Voucher đã hết hạn hoặc chưa đến hạn sử dụng."),
    VOUCHER_NOT_APPLICABLE(400, "MENU_400_VOUCHER_NOT_APPLICABLE", "Voucher không áp dụng được."),
    MENU_404_TOPPING_NOT_FOUND(404, "MENU_404_TOPPING_NOT_FOUND", "Không tìm thấy topping."),
    MENU_409_TOPPING_CODE_EXISTED(409, "MENU_409_TOPPING_CODE_EXISTED", "Mã topping đã tồn tại."),
    MENU_409_TOPPING_IN_USE(409, "MENU_409_TOPPING_IN_USE", "Topping đang được gán cho sản phẩm, không thể xóa. Vui lòng chuyển sang INACTIVE."),
    MENU_400_INVALID_TOPPING_DATA(400, "MENU_400_INVALID_TOPPING_DATA", "Dữ liệu topping không hợp lệ (materialId và materialQuantity phải đi kèm nhau)."),
    MENU_404_PRODUCT_TOPPING_NOT_FOUND(404, "MENU_404_PRODUCT_TOPPING_NOT_FOUND", "Không tìm thấy cấu hình topping của sản phẩm."),
    MENU_409_PRODUCT_TOPPING_EXISTED(409, "MENU_409_PRODUCT_TOPPING_EXISTED", "Sản phẩm đã được gán topping này."),
    MENU_400_INVALID_MAX_QUANTITY(400, "MENU_400_INVALID_MAX_QUANTITY", "Số lượng tối đa topping không hợp lệ (phải >= 1)."),
    MENU_409_PRODUCT_INACTIVE(409, "MENU_409_PRODUCT_INACTIVE", "Sản phẩm đang ngừng hoạt động, không thể thêm/sửa cấu hình topping."),
    MENU_400_NOT_COMBO_PRODUCT(400, "MENU_400_NOT_COMBO_PRODUCT", "Sản phẩm không phải Combo (isCombo = false)."),
    MENU_400_COMBO_EMPTY_ITEMS(400, "MENU_400_COMBO_EMPTY_ITEMS", "Combo phải có ít nhất một thành phần."),
    MENU_400_COMBO_INVALID_QUANTITY(400, "MENU_400_COMBO_INVALID_QUANTITY", "Số lượng thành phần Combo không hợp lệ (phải >= 1)."),
    MENU_400_COMBO_SELF_REFERENCE(400, "MENU_400_COMBO_SELF_REFERENCE", "Không thể thêm Combo vào chính nó."),
    MENU_409_COMBO_DUPLICATE_VARIANT(409, "MENU_409_COMBO_DUPLICATE_VARIANT", "Biến thể đã tồn tại trong Combo."),
    MENU_409_COMBO_ITEM_EXISTS(409, "MENU_409_COMBO_ITEM_EXISTS", "Sản phẩm/biến thể đã tồn tại trong Combo."),
    MENU_404_BRANCH_TOPPING_NOT_FOUND(404, "MENU_404_BRANCH_TOPPING_NOT_FOUND", "Không tìm thấy cấu hình topping chi nhánh."),
    MENU_403_OUT_OF_SCOPE(403, "MENU_403_OUT_OF_SCOPE", "Bạn không có quyền truy cập dữ liệu chi nhánh này."),
    ORDER_404_CART_NOT_FOUND(404, "ORDER_404_CART_NOT_FOUND", "Không tìm thấy giỏ hàng."),
    ORDER_404_PRODUCT_NOT_FOUND(404, "ORDER_404_PRODUCT_NOT_FOUND", "Không tìm thấy sản phẩm."),
    ORDER_404_ORDER_NOT_FOUND(404, "ORDER_404_ORDER_NOT_FOUND", "Không tìm thấy đơn hàng."),
    ORDER_404_DELIVERY_NOT_FOUND(404, "ORDER_404_DELIVERY_NOT_FOUND", "Không tìm thấy thông tin giao hàng."),
    ORDER_400_INVALID_QUANTITY(400, "ORDER_400_INVALID_QUANTITY", "Số lượng không hợp lệ hoặc vượt tồn kho."),
    ORDER_400_CART_EMPTY(400, "ORDER_400_CART_EMPTY", "Không thể tạo đơn khi giỏ hàng trống."),
    ORDER_400_INVALID_RECEIVER_DATA(400, "ORDER_400_INVALID_RECEIVER_DATA", "Thông tin người nhận không hợp lệ."),
    ORDER_400_INVALID_STATUS_TRANSITION(400, "ORDER_400_INVALID_STATUS_TRANSITION",
                                        "Chuyển trạng thái đơn không hợp lệ."),
    ORDER_400_ORDER_NOT_CANCELLABLE(400, "ORDER_400_ORDER_NOT_CANCELLABLE", "Đơn hàng không còn đủ điều kiện hủy."),
    ORDER_400_INVALID_PRICE(400, "ORDER_400_INVALID_PRICE", "Giá trị tiền/chi phí không hợp lệ."),
    ORDER_400_DELIVERY_FAILED(400, "ORDER_400_DELIVERY_FAILED", "Không thể cập nhật kết quả giao hàng."),
    ORDER_400_UNPAID(400, "ORDER_400_UNPAID", "Đơn hàng chưa thanh toán."),
    ORDER_403_OUT_OF_SCOPE(403, "ORDER_403_OUT_OF_SCOPE", "Tài khoản truy cập đơn/giao hàng ngoài phạm vi."),
    MENU_404_BRANCH_PRODUCT_NOT_FOUND(404, "MENU_404_BRANCH_PRODUCT_NOT_FOUND", "Không tìm thấy cấu hình sản phẩm chi nhánh."),

    // STORE module (006-store)
    STORE_404_SHIFT_NOT_FOUND(404, "STORE_404_SHIFT_NOT_FOUND", "Không tìm thấy khung ca làm việc."),
    STORE_404_ASSIGNMENT_NOT_FOUND(404, "STORE_404_ASSIGNMENT_NOT_FOUND", "Không tìm thấy phân ca làm việc."),
    STORE_404_REPORT_NOT_FOUND(404, "STORE_404_REPORT_NOT_FOUND", "Không tìm thấy biên bản chốt ca."),
    STORE_404_DAILY_REPORT_NOT_FOUND(404, "STORE_404_DAILY_REPORT_NOT_FOUND", "Không tìm thấy báo cáo ngày của chi nhánh."),
    STORE_409_SHIFT_CODE_EXISTS(409, "STORE_409_SHIFT_CODE_EXISTS", "Mã ca đã tồn tại trong chi nhánh."),
    STORE_409_ASSIGNMENT_EXISTS(409, "STORE_409_ASSIGNMENT_EXISTS", "Nhân viên đã được phân ca khác trong ngày."),
    STORE_409_DAILY_REPORT_EXISTS(409, "STORE_409_DAILY_REPORT_EXISTS", "Báo cáo ngày của chi nhánh đã tồn tại."),
    STORE_400_INVALID_HOURS(400, "STORE_400_INVALID_HOURS", "Giờ bắt đầu và kết thúc ca không hợp lệ."),
    STORE_400_INVALID_STATUS_TRANSITION(400, "STORE_400_INVALID_STATUS_TRANSITION", "Chuyển trạng thái ca không hợp lệ."),
    STORE_400_ACTIVE_SHIFT_EXISTS(400, "STORE_400_ACTIVE_SHIFT_EXISTS", "Nhân viên đang có ca làm việc chưa kết thúc."),
    STORE_400_ACTIVE_SHIFTS_REMAINING(400, "STORE_400_ACTIVE_SHIFTS_REMAINING", "Còn ca chưa hoàn thành, không thể chốt sổ ngày."),
    STORE_400_DIFFERENCE_REASON_REQUIRED(400, "STORE_400_DIFFERENCE_REASON_REQUIRED", "Bắt buộc nhập lý do khi tiền kiểm đếm thực tế bị lệch so với tiền lý thuyết."),
    STORE_400_DENOMINATION_MISMATCH(400, "STORE_400_DENOMINATION_MISMATCH", "Tổng tiền bảng kê mệnh giá không khớp với tiền thực đếm."),
    STORE_400_INVALID_CASH(400, "STORE_400_INVALID_CASH", "Số tiền mặt không hợp lệ."),
    STORE_403_OUT_OF_SCOPE(403, "STORE_403_OUT_OF_SCOPE", "Bạn không có quyền truy cập dữ liệu ca của chi nhánh này."),

    // REPORT module (report export)
    REPORT_400_SYNC_LIMIT_EXCEEDED(400, "REPORT_400_SYNC_LIMIT_EXCEEDED", "Dữ liệu vượt quá giới hạn an toàn cho xử lý đồng bộ. Vui lòng dùng chế độ ASYNC hoặc thu hẹp phạm vi báo cáo."),
    REPORT_400_UNSUPPORTED_TYPE(400, "REPORT_400_UNSUPPORTED_TYPE", "Loại báo cáo không được hỗ trợ cho phân hệ này."),
    REPORT_400_INVALID_FORMAT(400, "REPORT_400_INVALID_FORMAT", "Định dạng xuất file không được hỗ trợ."),

    // ORG & BRANCH module (002-branch & pickup slot)
    BRANCH_400_CODE_EXISTS(400, "BRANCH_400_CODE_EXISTS", "Mã chi nhánh đã tồn tại."),
    BRANCH_400_CANNOT_DELETE_ACTIVE_RESOURCES(400, "BRANCH_400_CANNOT_DELETE_ACTIVE_RESOURCES", "Không thể xóa chi nhánh đã phát sinh đơn hàng, kho hoặc ca làm việc."),
    BRANCH_HOURS_400_INVALID_TIMES(400, "BRANCH_HOURS_400_INVALID_TIMES", "Giờ mở và đóng cửa không hợp lệ. Giờ mở và đóng không được trùng nhau trừ khi đóng cửa cả ngày."),
    BRANCH_HOURS_404_NOT_FOUND(404, "BRANCH_HOURS_404_NOT_FOUND", "Không tìm thấy cấu hình giờ hoạt động."),
    PICKUP_SLOT_400_INVALID_TIME_RANGE(400, "PICKUP_SLOT_400_INVALID_TIME_RANGE", "Khung giờ pickup không hợp lệ: start_time phải nhỏ hơn end_time và kéo dài từ 15 đến 120 phút."),
    PICKUP_SLOT_404_NOT_FOUND(404, "PICKUP_SLOT_404_NOT_FOUND", "Không tìm thấy khung giờ pickup."),
    PICKUP_SLOT_409_CODE_EXISTS(409, "PICKUP_SLOT_409_CODE_EXISTS", "Mã khung giờ pickup đã tồn tại trong chi nhánh."),
    ORDER_400_SLOT_FULL(400, "ORDER_400_SLOT_FULL", "Khung giờ này đã kín đơn, vui lòng chọn khung giờ khác."),
    ORDER_400_BRANCH_CLOSED(400, "ORDER_400_BRANCH_CLOSED", "Chi nhánh hiện đang ngoài giờ hoạt động."),
    FIN_404_PAYABLE_NOT_FOUND(404, "FIN_404_PAYABLE_NOT_FOUND", "Không tìm thấy công nợ"),
    FIN_400_PAYABLE_INVALID_STATUS(400, "FIN_400_PAYABLE_INVALID_STATUS", "Trạng thái công nợ không cho phép thao tác này"),
    FIN_400_PAYABLE_AMOUNT_EXCEED(400, "FIN_400_PAYABLE_AMOUNT_EXCEED", "Số tiền thanh toán vượt quá số nợ còn lại"),
    FIN_400_PAYABLE_INVALID_AMOUNT(400, "FIN_400_PAYABLE_INVALID_AMOUNT", "Số tiền không hợp lệ"),
    FIN_404_SUPPLIER_NOT_FOUND(404, "FIN_404_SUPPLIER_NOT_FOUND", "Không tìm thấy nhà cung cấp"),
    FIN_404_PO_NOT_FOUND(404, "FIN_404_PO_NOT_FOUND", "Không tìm thấy đơn mua hàng"),
    FIN_400_PAYABLE_PO_NOT_RECEIVABLE(400, "FIN_400_PAYABLE_PO_NOT_RECEIVABLE",
            "Đơn mua hàng chưa ở trạng thái duyệt/nhận hàng, không thể liên kết công nợ"),
    FIN_400_PAYABLE_EXISTS_FOR_PO(409, "FIN_400_PAYABLE_EXISTS_FOR_PO",
            "Đơn mua hàng này đã được liên kết với công nợ khác"),
    FIN_400_PAYABLE_HAS_PAYMENTS(400, "FIN_400_PAYABLE_HAS_PAYMENTS",
            "Công nợ đã có lịch sử thanh toán, không thể xóa"),
    FIN_400_PAYABLE_CANNOT_EDIT(400, "FIN_400_PAYABLE_CANNOT_EDIT",
            "Chỉ có thể chỉnh sửa công nợ UNPAID chưa có hóa đơn và chưa có thanh toán"),
    FIN_400_PAYABLE_SUPPLIER_INACTIVE(400, "FIN_400_PAYABLE_SUPPLIER_INACTIVE",
            "Nhà cung cấp đang ngừng hoạt động"),
    FIN_400_PAYABLE_INVOICE_NO_DUPLICATE(409, "FIN_400_PAYABLE_INVOICE_NO_DUPLICATE",
            "Số hóa đơn đã tồn tại trong hệ thống"),
    FIN_404_EXPENSE_NOT_FOUND(404, "FIN_404_EXPENSE_NOT_FOUND", "Không tìm thấy khoản chi phí"),
    FIN_404_EXPENSE_BRANCH_NOT_FOUND(404, "FIN_404_EXPENSE_BRANCH_NOT_FOUND", "Không tìm thấy chi nhánh"),
    FIN_400_EXPENSE_FINALIZED_PERIOD(400, "FIN_400_EXPENSE_FINALIZED_PERIOD",
            "Ngày này thuộc kỳ tài chính đã chốt (FINALIZED), không thể thay đổi chi phí"),
    FIN_400_EXPENSE_INVALID_AMOUNT(400, "FIN_400_EXPENSE_INVALID_AMOUNT", "Số tiền chi phí không hợp lệ"),
    FIN_400_EXPENSE_INVALID_CATEGORY(400, "FIN_400_EXPENSE_INVALID_CATEGORY",
            "Loại chi phí không được để trống và tối đa 50 ký tự"),
    FIN_400_EXPENSE_INVALID_DATE(400, "FIN_400_EXPENSE_INVALID_DATE", "Ngày chi phí không hợp lệ"),
    FIN_404_BRANCH_NOT_FOUND(404, "FIN_404_BRANCH_NOT_FOUND", "Không tìm thấy chi nhánh"),
    FIN_404_FINANCIAL_SUMMARY_NOT_FOUND(404, "FIN_404_FINANCIAL_SUMMARY_NOT_FOUND",
                                        "Không tìm thấy báo cáo tài chính của ngày"),
    FIN_400_INVALID_PERIOD(400, "FIN_400_INVALID_PERIOD", "Khoảng thời gian hoặc ngày kinh doanh không hợp lệ"),
    FIN_409_SUMMARY_ALREADY_FINALIZED(409, "FIN_409_SUMMARY_ALREADY_FINALIZED",
                                      "Báo cáo đã được chốt (FINALIZED), không thể tính lại hoặc chốt lần nữa"),
    FIN_409_SOURCE_DATA_MISSING(409, "FIN_409_SOURCE_DATA_MISSING",
                                "Thiếu dữ liệu nguồn cần thiết để tổng hợp báo cáo"),
    FIN_409_RECONCILIATION_MISMATCH(409, "FIN_409_RECONCILIATION_MISMATCH",
                                    "Số tổng hợp không khớp dữ liệu nguồn, vui lòng tính lại trước khi chốt"),
    FIN_403_OUT_OF_SCOPE(403, "FIN_403_OUT_OF_SCOPE", "Bạn không có quyền truy cập dữ liệu chi nhánh này"),

    KDS_404_TICKET_NOT_FOUND(404, "KDS_404_TICKET_NOT_FOUND", "Không tìm thấy phiếu bếp."),
    KDS_404_TICKET_ITEM_NOT_FOUND(404, "KDS_404_TICKET_ITEM_NOT_FOUND", "Không tìm thấy món trong phiếu bếp."),
    KDS_400_INVALID_STATUS_TRANSITION(400, "KDS_400_INVALID_STATUS_TRANSITION",
                                        "Chuyển trạng thái bếp không hợp lệ."),
    KDS_400_INVALID_QUANTITY(400, "KDS_400_INVALID_QUANTITY", "Số lượng hoàn tất không hợp lệ."),
    KDS_400_INVALID_STATION(400, "KDS_400_INVALID_STATION", "Trạm bếp không hợp lệ. Hệ thống chỉ dùng trạm BAR.");
    private final int statusCode;
    private final String code;
    private final String message;

    ErrorCode(int statusCode, String code, String message) {
        this.statusCode = statusCode;
        this.code = code;
        this.message = message;
    }

    /**
     * Lấy HTTP status code tương ứng với mã lỗi.
     */
    public int getStatusCode() {
        return statusCode;
    }

    /**
     * Lấy mã lỗi nội bộ (ví dụ: ERR_401).
     */
    public String getCode() {
        return code;
    }

    /**
     * Lấy thông báo mặc định của mã lỗi.
     */
    public String getMessage() {
        return message;
    }
}
